// <auto-generated />
namespace Windows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contratofieldsremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contratofieldsremove));
        
        string IMigrationMetadata.Id
        {
            get { return "202205121638548_contrato-fields-remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
